name: api_helper
description: Api Helper based on Dio
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  custom_response: ^0.0.1
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
